### ISSUE TITLE
New-MVPContribution returning 500 internal server error

### ISSUE THREAD

**Issue by wsmelton** [lazywinadmin/MVP#19]
Not to sure why this error is being returned.

I did try just entering a test, single, contribution and it does not show upon the site either. I am able to manually add one via the web site so I know the block has been removed now.

```powershell
> $Error[0] | select *


PSMessageDetails      :
Exception             : System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
                           at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
                           at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
TargetObject          : System.Net.HttpWebRequest
CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
ErrorDetails          : {"ClassName":"System.InvalidOperationException","Message":"Nullable object must have a
                        value.","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at
                        System.Nullable`1.get_Value()\r\n   at
                        Microsoft.Support.Mvp.Private.API.ContributionsController.PostContribution(ContributionsModel
                        model) in D:\\a\\1\\s\\src\\Microsoft.MVP.Web\\API\\ContributionsController.cs:line 219","Remot
                        eStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":"8\nget_Value\nmscorlib,
                        Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\nSystem.Nullable`1\nT
                        get_Value()","HResult":-2146233079,"Source":"mscorlib","WatsonBuckets":null}
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at New-MVPContribution<Process>, C:\Program
                        Files\WindowsPowerShell\Modules\MVP\0.0.2.0\Public\New-MVPContribution.ps1: line 178
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}



07-01 16:04:54 C:\WINDOWS\system32 17ms
> New-MVPContribution -StartDate '05/01/2018' -Title 'Testing 123' -Description 'This is just testing the MVP Module' -A
nnualQuantity 1 -SecondAnnualQuantity 0 -AnnualReach 0 -Visibility EveryOne -ContributionTechnology PowerShell

cmdlet New-MVPContribution at command pipeline position 1
Supply values for the following parameters:
ContributionType: Article


ContributionId         : 901526
ContributionTypeName   : Article
ContributionType       : @{Id=e36464de-179a-e411-bbc8-6c3be5a82b68; Name=Article; EnglishName=Article}
ContributionTechnology : @{Id=7cc301bb-189a-e411-93f2-9cb65495d3c4; Name=PowerShell; AwardName=; AwardCategory=}
StartDate              : 2018-05-01T00:00:00
Title                  : Testing 123
ReferenceUrl           : https://github.com/lazywinadmin/MVP
Visibility             : @{Id=299600000; Description=Public; LocalizeKey=}
AnnualQuantity         : 1
SecondAnnualQuantity   : 0
AnnualReach            : 0
Description            : This is just testing the MVP Module



07-01 16:07:48 C:\WINDOWS\system32 20ms
> Get-MVPContribution -ID 901526


ContributionId         : 901526
ContributionTypeName   : Article
ContributionType       : @{Id=e36464de-179a-e411-bbc8-6c3be5a82b68; Name=Article; EnglishName=Article}
ContributionTechnology : @{Id=7cc301bb-189a-e411-93f2-9cb65495d3c4; Name=PowerShell; AwardName=; AwardCategory=}
StartDate              : 2018-05-01T00:00:00
Title                  : Testing 123
ReferenceUrl           : https://github.com/lazywinadmin/MVP
Visibility             : @{Id=299600000; Description=Public; LocalizeKey=}
AnnualQuantity         : 1
SecondAnnualQuantity   : 0
AnnualReach            : 0
Description            : This is just testing the MVP Module



07-01 16:08:42 C:\WINDOWS\system32 20ms
```

**Comment by lazywinadmin** [comment]
Thanks for reporting this issue @wsmelton 
I'm not able to reproduce the error.

Regarding the MVP website not showing your entries, I now it can take some times to show after using the API. The only workarounds i found are here: https://github.com/lazywinadmin/MVP/issues/15

**Comment by raffaeler** [comment]
In my case the 500 error happened because of an accented letter in the title. As I removed the accent, the submission succeeded.
Il looks like the API does not allow Unicode characters so I opened a ticket with MS for that.
Take a look to your CSV file with an hex editor and see if there is unicode char due to copy/paste.

**Comment by raffaeler** [comment]
I was informed by the MVP API team that the `New-MVPContribution.ps1` script is missing the content type:
```
ContentType = 'application/json; charset=utf-8'
```
After adding that line to the script, the submission using "C3 A0" to represent the "à" letter was successful.

**Comment by lazywinadmin** [comment]
Thanks for the info @raffaeler I guess i could include this in the code.

**Comment by wsmelton** [comment]
Any luck in addressing this issue? I'm stilling unable to use the module because of this error.

```
VERBOSE: About to create a new contribution with Body {
  "ContributionId": 0,
  "ContributionTypeName": "Non-Microsoft Open Source Projects",
  "ContributionType": {
    "Id": "414bcf30-e889-e511-8110-c4346bac0abc",
    "Name": "Non-Microsoft Open Source Projects",
    "EnglishName": "Non-Microsoft Open Source Projects"
  },
  "ContributionTechnology": {
    "Id": "7cc301bb-189a-e411-93f2-9cb65495d3c4",
    "Name": "PowerShell",
    "AwardName": "Cloud and Datacenter Management",
    "AwardCategory": "My Awarded Category"
  },
  "AdditionalTechnologies": [
    {
        "Id": "",
        "Name": "",
        "AwardName": "",
        "AwardCategory": ""
    }
  ],
  "StartDate": "43808",
  "Title": "appveyor-ci Appveyor SQL Server 2019 Build Image",
  "ReferenceUrl": "https://github.com/appveyor/ci/issues/3243",
  "Visibility": {
    "Id": 299600000,
    "Description": "Everyone",
    "LocalizeKey": "PublicVisibilityText"
  },
  "AnnualQuantity": 1,
  "SecondAnnualQuantity": 0,
  "AnnualReach": 0,
  "Description": "Issue contribution to open source projects"
}
VERBOSE: POST https://mvpapi.azure-api.net/mvp/api/contributions with -1-byte payload
WARNING: Failed to invoke the PostContribution API because The remote server returned an error: (500) Internal Server Error.
```

**Comment by wsmelton** [comment]
Disregard. This is because I'm using Doug's module to pull data from Excel.
